# GitHub Pages configuration for Development Station SPA
title: Development Station
description: Professional developer utilities that work offline. 50+ free online tools.
url: "https://developmentstation.github.io"
baseurl: ""

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from Jekyll processing
exclude:
  - README.md
  - requirements.md
  - node_modules/
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Include files that start with underscore
include:
  - _headers
  - _redirects

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO
lang: en
author: Development Station
twitter:
  username: developmentstation
  card: summary_large_image

# Social media
social:
  name: Development Station
  links:
    - https://developmentstation.github.io

# Analytics (if needed)
google_analytics: # Add your GA tracking ID here if needed
